### ISSUE TITLE
Change signature the of UpdateJobStatus interface ?

### ISSUE THREAD

**Issue by SimonCqk** [alibaba/kubedl#10]
In the previous `ControllerInterface` design, the `UpdateJobStatus` method is as follows: 

```go
// UpdateJobStatus updates the job status and job conditions
UpdateJobStatus(job interface{}, replicas map[ReplicaType]*ReplicaSpec, jobStatus *JobStatus) error
```

when its comes to decide whether a job should restart or not, we check the pod exit code and phase，in tf-operator implementation [restart](https://github.com/kubeflow/tf-operator/blob/master/pkg/controller.v1/tensorflow/pod.go#L117), a `restart` bool is used and can be passed to `updateSingleJobStatus`, but now limited by interface design, we can only determine whether to restart by simply [compare restartpolicy](https://github.com/alibaba/kubedl/blob/master/controllers/tensorflow/status.go#L185), which may cause a bug. In another way we can recompute the `restart` flag by iterating all pods again, but it quite inefficient.

so I propose to change the `UpdateJobStatus` signature to:

```go
UpdateJobStatus(job interface{}, replicas map[ReplicaType]*ReplicaSpec, jobStatus *JobStatus, restart bool) error`
```

and the restarting mechanism is required by all workload controllers.

**Comment by jian-he** [comment]
lgtm
