### ISSUE TITLE
example of pytorch job has error value about rank num

### ISSUE THREAD

**Issue by jiaqianjing** [alibaba/kubedl#52]
![image](https://user-images.githubusercontent.com/16071449/85967114-3de81480-b9f4-11ea-8572-ccf6dd3d5c7c.png)

**Comment by SimonCqk** [comment]
@jiaqianjing hi, it's a known issue and I will fix it soon.

**Comment by jiaqianjing** [comment]
ok, 3q. And why not use the community's  pytorch operator directly? 
Now it looks like you've rewritten it（pytorch crd and controller）

**Comment by SimonCqk** [comment]
@jiaqianjing It's a known issue and has been fixed in code, however it seems that the docker image is not up to date, I'll re-build-and-push it soon.

**Comment by SimonCqk** [comment]
> ok, 3q. And why not use the community's pytorch operator directly?
> Now it looks like you've rewritten it（pytorch crd and controller）

we have not regenerate the crd or rewrite the controller, we refactor the original controllers implementations in `kubebuilder` style and redesign the framework, hence we are able to deliver new generic/pluggable features, if there will be some extensions, it will be totally backward compatible.

**Comment by jiaqianjing** [comment]
Could you give your DingDing num? U can send an email to this mailbox：jiaqianjing1992@163.com

**Comment by SimonCqk** [comment]
fixed.
